### ISSUE TITLE
Json.NET list/array deserialization

### ISSUE THREAD

**Issue by REHERC** [Ciastex/Centrifuge#11]
Calling Settings.GetItem<T>(string key) with types like T[] (arrays) or List<T> throws an exception

There is a workaround to that: `Settings;GetItem<JArray>(...).ToObject<type mentioned above>()`

Example: `Settings;GetItem<JArray>("MyList").ToObject<List<string>>()`

**Comment by vddCore** [comment]
could you use like, C# or something, need more details
