### ISSUE TITLE
Problem with Log class and new line char

### ISSUE THREAD

**Issue by REHERC** [Ciastex/Centrifuge#12]
Logging text to the console with "\n" in it won't put the new line to the left-most cell in the terminal. instead it just shifts the cursor down one line and continues at the same horizontal position. using \r\n instead fxed the problem(edited)
[16:10]
(centrifuge 2.3.0)

Example with \n:
```text
[16:08:17 INF] [Analytics__LogEvent] Analytics request:
                                                         Page: Distance_6895
                                                                              Category: Global
```

Example with \r\n:
```text
[16:08:17 INF] [Analytics__LogEvent] Analytics request:
  Page: Distance_6895
  Category: Global
```

**Comment by REHERC** [comment]
Suggested bugfix: replace \n with \r\n before displaying the value.

Note: the bug also happens in the log file.

**Comment by vddCore** [comment]
this will get more attention after 3.x release

**Comment by REHERC** [comment]
The assets files can be found here: https://drive.google.com/drive/folders/1m_2ew4f8D2wuqe2fpwjZirSrk4X1NzaK?usp=sharing

I opened them in AssetStudio (https://github.com/Perfare/AssetStudio/releases) and it reads them fine (even detects unity 5.5.5f1 as the unity version that made them)

**Comment by vddCore** [comment]
fixed with updated release artifacts
