### ISSUE TITLE
Assets.Bundle is always null

### ISSUE THREAD

**Issue by REHERC** [Ciastex/Centrifuge#13]
In my mod folder i have a file in the Assets folder called "countdown" and in my code i do the following:
```csharp
var assets = new Assets("countdown");
```
But the assets.Bundle value is null.
I tried to cast it to the AssetBundle type but it remains null.

However, Centrifuge doesn't complain when loading the assets file and prints the following in the console after instantiating the Assets instance:
```
[01:57:14 INF] [Assets] Loaded asset bundle C:\Program Files (x86)\Steam\steamapps\common\Distance\Distance_Data\Centrifuge\Mods\Distance Nitronic HUD\Assets\countdown
```

I also tried to use different file names (both in the code and as a file name at the same time) like countdown.assets with no success.

Other potentially useful infos:
Game i'm modding: Distance
Unity version: ~5.5
.Net version: 3.5 (mono)

**Comment by REHERC** [comment]
After digging, i managed to load the asset bundle by following this piece of documentation: https://docs.unity3d.com/550/Documentation/ScriptReference/WWW-assetBundle.html

**Comment by REHERC** [comment]
While this solution probably isn't going to be 100% game agnostic, i made an alternate Assets.Load using the WWW class that looks like this (and works in unity 5.5)

```csharp
private AssetBundle Load()
{
		try
		{
				if (!File.Exists(FilePath))
				{
						throw new FileNotFoundException(FilePath);
				}

				string urlPath = FilePath.ToLowerInvariant()
				.Replace(Path.DirectorySeparatorChar, '/')
				.Replace(Path.AltDirectorySeparatorChar, '/');

				WWW www = new WWW($"file:///{urlPath}");

				var assetBundle = www.assetBundle;

				Log.Info($"Loaded asset bundle {FilePath}");

				return assetBundle;
		}
		catch (Exception ex)
		{
				Log.Exception(ex);
				return null;
		}
}
```

**Comment by vddCore** [comment]
Thanks for the report. Will look into this now.

**Comment by vddCore** [comment]
Can you provide the asset bundle in question?

**Comment by REHERC** [comment]
The assets files can be found here: https://drive.google.com/drive/folders/1m_2ew4f8D2wuqe2fpwjZirSrk4X1NzaK?usp=sharing

I opened them in AssetStudio (https://github.com/Perfare/AssetStudio/releases) and it reads them fine (even detects unity 5.5.5f1 as the unity version that made them)

**Comment by vddCore** [comment]
From Distance discord convo: the whole thing works. Remember to use `Load()` optional callback in order to load any assets, textures or sounds.
