### ISSUE TITLE
install_linux.sh has a carriage return in the release zips

### ISSUE THREAD

**Issue by Seeker14491** [Ciastex/Centrifuge#16]
The `install_linux.sh` script included in the current release zips (Centrifuge.3.2.1.net35.zip and Centrifuge.3.2.1.netstandard.zip) has a carriage return character which causes the script to fail.

**Comment by ghost** [comment]
I can confirm the issue. The carriage return character is not present in the original source file of install_linux.sh, but somehow the build process adds it.

I fixed another issue with the file in #17 (BOM messing up the shebang), but the carriage return problem persists.
This error is displayed when executing the file:

```txt
bash: ./install_linux.sh: /bin/bash^M: bad interpreter: No such file or directory
```

**Comment by ghost** [comment]
Ok, I dug deeper and I think I realized somewhat what's happening: The default settings for git on Windows is to checkout the files with CRLF endings and commit them with LF endings. So if you are on a Windows system and add the current files to a zip folder, they will have CRLF endings, even though the original source would only have LF endings.

I corrected that by configuring the .gitattributes file to always checkout .sh files with LF endings and converted the existing files to only have LF endings. PR is #18

For the scripts to correctly work, both #17 and #18 will have to be merged.

**Comment by vddCore** [comment]
Many thanks for the PRs! I have updated the existing latest release ZIPs as well.
