### ISSUE TITLE
Reactor.API.Configuration.Settings don't get loaded properly on restart

### ISSUE THREAD

**Issue by ghost** [Ciastex/Centrifuge#9]
When trying to load settings by creating a new instance of `Settings` with the existing `fileName`, the settings don't get loaded but rather an empty Settings object is returned.

I've demonstrated the behaviour with the following xUnit tests (RetreiveSameInstance passes, but RetreiveSecondInstance fails):

```cs
// This passes
[Fact]
public void RetreiveSameInstance()
{
    Settings test = new Settings("same_settings");
    test.Add("testValue", 15);
    test.Save();

    int result = test.GetOrCreate<int>("testValue", 8);
    
    Assert.Equal(15, result);
}

// This fails
[Fact]
public void RetreiveSecondInstance()
{
    Settings test = new Settings("second_settings");
    test.Add("testValue", 15);
    test.Save();

    int initial = test.GetOrCreate<int>("testValue", 8);

    test = new Settings("second_settings");

    int second = test.GetOrCreate<int>("testValue", 8);

    Assert.Equal(initial, second);
}
```

I suspect that line number 35 in Settings.cs the culprit:
https://github.com/Ciastex/Centrifuge/blob/e5e000b244f13f1e1f3bfe9e7e10397b3d6a2f20/Reactor.API/Configuration/Settings.cs#L35
Here, the values are loaded from the file, but never assigned to the later processed Section used to populate the new Settings instance.

I changed the code in my fork to directly load the data into the Section and it seems to work with this fix:
https://github.com/DropNib/Centrifuge/blob/662869a67f918cc07843782e59a65e9f02c05baf/Reactor.API/Configuration/Settings.cs#L35
I can create a PR, if this is the desired behaviour.

**Comment by vddCore** [comment]
Hah, thanks for the report, I've noticed that when porting the system to Centrifuge and forgot to backport the fix to Spectrum. PR is very much welcome.
